server:
  port: 8080

spring:
  http:
    encoding:
      charset: UTF-8


simple-pay:
  #统一配置支付通知地址
  notify-url: http://www.baidu.com
  #統一配置退款通知地址
  refund-notify-url: http://www.baidu.com
  #統一H5跳转地址
  redirect-url: https://www.baidu.com
  #微信支付配置
  wechat-pay:
    #商户号
    mchid: 1603374952
    #pk12凭证路径取classPath路径下文件-无退款功能可省略
    pk12-path: 7bbd824f3836467fa1f7071d1a9cf0ca.p12
    #微信公众平台appId
    woa-app-id: wx72c8c8485611f383
    #微信开放平台appId
    wpp-app-id: wxa0cc46db3c2c4aa4
    #签名key
    sign-key: 4366744fbc624b5e9038274052998ab7
  #支付宝支付配置
  alipay:
    #appId
    app-id: 2021001199681089
    #alipay 公钥
    ali-pay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyP7UcGaXCj1SaWD9EXWSODW9mynyXkOZEE3qzLZmGPZe7BESu3/yPuQ3evDevAqvZFlp5KWKuXIIDWbDO5afaO8Yd2PzWGfTrsOPdCHtAO2pegH49YGXW/wHVWgDaFUhOMmMCnnaSDnLoyS+k0OCVtMvZXGI4vDkpPgIbwrRArBaCvZepWuja9cL52cRhUL2Ep/lrlWtjIU+LYgEnWFzulkjeJaRKhrJrqOCSQ3UY7mntwUf8nSpulbYO8vXEBYS3k3WFVFqVZbCW9PTISOFHJboEFFJHxv6mBk3MUzSOW62tV6wIfFUOcBhFGj40G9OPyStuuIqiypZFZPx277FhwIDAQAB
    #私钥
    private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDMl6LdTyXCIDR/8S+zgLRZiXmAOtoq3E00KzsiNnuzpxpJDHL1ugQ+O+w0owjnO8Lipa7IVzLLQqwYYfJuylVsWjKTcXfGkpLQzuKwCW090PdhEBpnc/OiVtHoF7flOqLYpLagl4t2A2mYE94PgS97UToylRH4kzieM2jNY/n8VH8HcTCqSmk4O4GXs9K51GVzM4cesRssJDOXdc13a6Wf6sBm8OtA3f74dkTndRyJhEgytKwWNqDerUCt6ZQ+8jc/+ztOEL1P99kyScuTcvYwr121yijuuRU3xf0SdiY0dut3ACXE78z5TPNQqFRitykgAjhcLNWP/s9o1PunCLSFAgMBAAECggEBAMOtMBbM8UcW+D96FW5wZY3RX4TWRP2DUM/ZnSgexfdQlmJRZs5AyHghZcv+NrC6Rq3xWxa/15PyQ5jabT2rhUIpjn/YoX8phwPxK3zEt1fNOhz6gtZ5XwbgVMjPjpHOoBvmhclYyAjqQJ80OUnI+/nM+YWRb+u4GwmsD8uJmHnNPQE61F3CFauAIKcVG07Qi7jZG03x1cmswYW4TleMUlc/3wd1sTwWsmH9mwWqGJXxkA0wJJrKzmwDXtGHr0TWP0Nhnjltw8vupCbuHo3d4ahs/ZQEgG1UZNx3Ld0gPYi3n9aJKewsAmkvtB1ZILcLNQb+KIHH33a9iyr4hrYn1SECgYEA6jZ7knUV97NZx4uESw0sa55xSB2w98yn88dYmx3tJeO+rl7af2/OWT61MZC2HkEaG5u7bBUe0TxO+9zal+yQpEhq0Jv/FeGpQuGfb7wm/4EMITnGz7IoUk60wUkCOmg0U8aXhxe3zL/ilUTtX0kXX76LDPEWT9bTSA2yO9JVC9kCgYEA35/GQWixMmIwAehigcwx2e2SIT4JtV80lV/ZWaPRvB8MkW2F8d9Qropfry+IkAB703QlqHck8vBGUNpklSEEilKG/O/15rIp6TSDHKm6U/vRKrbTKFmH+bym2xjUChULI7O4jrXR/w0jdfh/N81WE0EhXxEnJ/wnjiI1LKFj3o0CgYAu0ddgDrHmg17mKfi3PBnuJY1FulG/J5VHgUkwMQpQMbfTibiqEwKwCn4UO3Z8k80RSc9sqsgvUZwEc0Drb+n2PVfE/fo/OI4qhYnmvzkYiIaROciJinbPBVbS8LJWVLBpMuDlq5MdhhpYdp/xFV5r0F5hpuwr56jy1XIUzVYc+QKBgDZiItLRZRZ9rnMoUpyCTjVTg1A2SCIlryIMl00ne+AmJOZRHlv+FR79Y9u00Z9DntmDy4y2vPOf31nWYtOpnfMNsupcaQ7bkTm3nZMg68F04h9jKuMLMvhXGrT5ysdQ6s6Z7G44ZYODbHZKIpYth5tTIYx/HWip9+ynAQuDjEgZAoGARnJ4jFB+Uc4rfFMbb1oz4/8SVhwfDqmGuQHTAhcA+snH0DmsDvwBxO1h7EbpyXBJHPDUy8JOUKDQc9dcVFNTb7mLYtxrGXZHaH+1oIXGvX3pp6lARemDExcsDJusTjR58U38rdtv7BMpidoBdPWIrW2sSpT1JfoZ1dWBEKtDhes=

